name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Debug Environment Variables
        env:
          ami: ${{ vars.AMI }}
          instance_type: ${{ vars.INSTANCE_TYPE }}
        run: |
          echo "AMI: $ami"
          echo "INSTANCE_TYPE: $instance_type"

      - name: Terraform Plan
        env:
          ami: ${{ vars.AMI }}
          instance_type: ${{ vars.INSTANCE_TYPE }}
        run: terraform plan -var="ami=$ami" -var="instance_type=$instance_type" -out=tfplan

      - name: Terraform Apply
        env:
          ami: ${{ vars.AMI }}
          instance_type: ${{ vars.INSTANCE_TYPE }}
        run: terraform apply -auto-approve tfplan
